# vim: set shiftwidth=2 tabstop=2 softtabstop=-1 expandtab:

sudo: required

branches:
  only:
  - master

services:
  - docker

before_script:
  - docker --version

script:
  - docker build --tag yanqd0/gitbook .
  - docker run yanqd0/gitbook which gitbook
